# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Bus')),
                ('n_seat', models.PositiveSmallIntegerField(verbose_name='Número de asiento')),
            ],
            options={
                'verbose_name_plural': 'Buses',
                'verbose_name': 'Bus',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
                'verbose_name': 'Ciudad',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.PositiveSmallIntegerField(verbose_name='Número de asiento')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('identification', models.PositiveIntegerField(verbose_name='Número de cédula')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('city_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_tickets', to='api.City', verbose_name='Ciudad Destino')),
                ('city_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_tickets', to='api.City', verbose_name='Ciudad Origen')),
            ],
            options={
                'verbose_name_plural': 'Tickets',
                'verbose_name': 'Ticket',
            },
        ),
    ]
